### PR TITLE
refactor: rename component const CoherenceSessionComponent to SessionBasedComponent

### PR DESCRIPTION
**Pull request by rpadrela**

### CODE REVIEW

**Review by kingstone426 — CHANGES_REQUESTED** [review]
Wasn't it SessionBased without Component?

**Comment by rpadrela** [comment]
> Wasn't it SessionBased without Component?

the const has Component in it. The value of the const, which is what is part of the generated code, does not.

**Comment by rpadrela** [comment]
> > Wasn't it SessionBased without Component?
> 
> the const has Component in it. The value of the const, which is what is part of the generated code, does not.

To clarify,

const SessionBasedComponent = "SessionBased"

SessionBased is what becomes part of the the C# code.

**Review by kingstone426 — APPROVED** [review]
Thanks for clarifying!

**Pull request merged**
